steps:

- id: 'Instalando GO ...'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'app']
  env: ['GOPATH=.']

- id: 'Executando teste ...'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v','./...']
  env: ['GOPATH=.']

- id: 'Criando Build da Imagem ...'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/app', '.']

images: ['gcr.io/$PROJECT_ID/app']
